version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
    - 8082:8080
    - 50000:50000
    volumes:
    - /home/sas/jenkins:/var/jenkins_home
    environment:
    - JAVA_OPTS="-XX:MaxPermSize=512m -Xms512m -Xmx1024m"
    links:
    - agent
    networks:
    - gems

  agent:
    build: ./agent
    links:
    - geminabox
    expose:
    - 22
    ports:
    - "22"
    networks:
    - gems

  geminabox:
    build: ./geminabox
    expose:
    - 22
    ports:
    - "22"
    - "8081:8080"
    networks:
    - gems

networks:
  gems: