version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /home/sas/jenkins:/var/jenkins_home
    environment:
    - JAVA_OPTS="-XX:MaxPermSize=512m -Xms512m -Xmx1024m"
    links:
    - agent
  agent:
    build: ./agent
    expose:
    - 22
    ports:
    - "22"